package models;

import java.util.Map;

import model.Column;
import model.Model;
import model.Table;

@Table("gameserver")
public class GameServer extends Model
{
	@Column(columnName="name", methodName="setName", methodParameter=String.class, primaryKey=true, length=100)
	private String name;
	
	@Column(columnName="nodeowner", methodName="setNodeOwner", methodParameter=String.class, length=100, foreignKey="node.name")
	private String nodeOwner;
	
	@Column(columnName="specificid", methodName="setSpecificID", methodParameter=Integer.class)
	private Integer specificID;
	
	@Column(columnName="servertype", methodName="setServerType", methodParameter=String.class, length=45)
	private String serverType;
	
	@Column(columnName="executablename", methodName="setExecutableName", methodParameter=String.class, length=100)
	private String executableName;
	
	public GameServer(String name, String nodeOwner, Integer specificID, String serverType, String executableName)
	{
		setName(name);
		setNodeOwner(nodeOwner);
		setSpecificID(specificID);
		setServerType(serverType);
		setExecutableName(executableName);
	}
	
	public GameServer(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}
	
	public void setExecutableName(String executableName)
	{
		if(checkVariable(this.executableName, executableName))
		{
			changed = true;
			this.executableName = executableName;
		}
	}
	
	public void setName(String name)
	{
		if(checkVariable(this.name, name))
		{
			changed = true;
			this.name = name;
		}
	}
	
	public void setNodeOwner(String nodeOwner)
	{
		if(checkVariable(this.nodeOwner, nodeOwner))
		{
			changed = true;
			this.nodeOwner = nodeOwner;
		}
	}
	
	public void setSpecificID(Integer specificID)
	{
		if(checkVariable(this.specificID, specificID))
		{
			changed = true;
			this.specificID = specificID;
		}
	}
	
	public void setServerType(String serverType)
	{
		if(checkVariable(this.serverType, serverType))
		{
			changed = true;
			this.serverType = serverType;
		}
	}
	
	public String getName()
	{
		return name;
	}
	
	public String getNodeOwner()
	{
		return nodeOwner;
	}
	
	public Integer getSpecificID()
	{
		return specificID;
	}
	
	public String getServerType()
	{
		return serverType;
	}
	
	public String getExecutableName()
	{
		return executableName;
	}
	
	protected void resetAutoGenerated()
	{
		
	}
}
