package models;

import java.util.Map;

import model.Column;
import model.Model;
import model.Table;

@Table("node")
public class Node extends Model
{
	@Column(columnName="name", methodName="setName", methodParameter=String.class, primaryKey=true, length=100)
	private String name;
	
	@Column(columnName="ram", methodName="setRAM", methodParameter=Integer.class)
	private Integer ram;
	
	public Node(String name, Integer ram)
	{
		setName(name);
		setRAM(ram);
	}
	
	public Node(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}
	
	public void setName(String name)
	{
		if(checkVariable(this.name, name))
		{
			changed = true;
			this.name = name;
		}
	}
	
	public String getName()
	{
		return name;
	}
	
	public void setRAM(Integer ram)
	{
		if(checkVariable(this.ram, ram))
		{
			changed = true;
			this.ram = ram;
		}
	}
	
	public Integer getRAM()
	{
		return ram;
	}
	
	protected void resetAutoGenerated()
	{
		
	}
}
