package models;

import java.util.Map;

import model.Column;
import model.Model;
import model.Table;

@Table("triggers")
public class Triggers extends Model
{
	@Column(columnName="id", methodName="setID", methodParameter=Integer.class, primaryKey=true, autoGenerated=true)
	private Integer id;
	
	@Column(columnName="type", methodName="setType", methodParameter=String.class)
	private String type;
	
	@Column(columnName="command", methodName="setCommand", methodParameter=String.class)
	private String command;
	
	@Column(columnName="value", methodName="setValue", methodParameter=String.class)
	private String value;
	
	@Column(columnName="serverowner", methodName="setServerOwner", methodParameter=String.class)
	private String serverowner;
	
	@Column(columnName="extra", methodName="setExtra", methodParameter=String.class)
	private String extra;
	
	public Triggers(String type, String command, String value, String serverowner, String extra)
	{
		setType(type);
		setCommand(command);
		setValue(value);
		setServerOwner(serverowner);
		setExtra(extra);
	}
	
	public Triggers(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}

	public Integer getID()
	{
		return id;
	}

	public String getType()
	{
		return type;
	}

	public String getCommand()
	{
		return command;
	}

	public String getValue()
	{
		return value;
	}
	
	public String getServerOwner()
	{
		return serverowner;
	}
	
	public String getExtra()
	{
		return extra;
	}

	public void setID(Integer id)
	{
		this.id = id;
	}

	public void setType(String type)
	{
		if(checkVariable(this.type, type))
		{
			changed = true;
			this.type = type;
		}
	}

	public void setCommand(String command)
	{
		if(checkVariable(this.command, command))
		{
			changed = true;
			this.command = command;
		}
	}

	public void setValue(String value)
	{
		if(checkVariable(this.value, value))
		{
			changed = true;
			this.value = value;
		}
	}
	
	public void setServerOwner(String serverowner)
	{
		if(checkVariable(this.serverowner, serverowner))
		{
			changed = true;
			this.serverowner = serverowner;
		}
	}
	
	public void setExtra(String extra)
	{
		if(checkVariable(this.extra, extra))
		{
			changed = true;
			this.extra = extra;
		}
	}
	
	protected void resetAutoGenerated()
	{
		setID(-1);
	}
}
